# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(667, 447)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plot = QtWidgets.QWidget(self.centralwidget)
        self.plot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plot.setObjectName("plot")
        self.plothl = QtWidgets.QHBoxLayout(self.plot)
        self.plothl.setContentsMargins(0, 0, 0, 0)
        self.plothl.setObjectName("plothl")
        self.verticalLayout.addWidget(self.plot)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.InputBox = QtWidgets.QLineEdit(self.centralwidget)
        self.InputBox.setMaximumSize(QtCore.QSize(16777215, 27))
        self.InputBox.setObjectName("InputBox")
        self.horizontalLayout.addWidget(self.InputBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_min = QtWidgets.QLabel(self.centralwidget)
        self.lb_min.setObjectName("lb_min")
        self.horizontalLayout_3.addWidget(self.lb_min)
        self.XMin = QtWidgets.QLineEdit(self.centralwidget)
        self.XMin.setObjectName("XMin")
        self.horizontalLayout_3.addWidget(self.XMin)
        self.XMax = QtWidgets.QLineEdit(self.centralwidget)
        self.XMax.setObjectName("XMax")
        self.horizontalLayout_3.addWidget(self.XMax)
        self.lb_pts = QtWidgets.QLabel(self.centralwidget)
        self.lb_pts.setObjectName("lb_pts")
        self.horizontalLayout_3.addWidget(self.lb_pts)
        self.Points = QtWidgets.QLineEdit(self.centralwidget)
        self.Points.setObjectName("Points")
        self.horizontalLayout_3.addWidget(self.Points)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 667, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(12, 12))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.actionLoad.setIcon(icon)
        self.actionLoad.setObjectName("actionLoad")
        self.actionStart = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("media-playback-start")
        self.actionStart.setIcon(icon)
        self.actionStart.setObjectName("actionStart")
        self.actionSelect_Folder = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("folder")
        self.actionSelect_Folder.setIcon(icon)
        self.actionSelect_Folder.setObjectName("actionSelect_Folder")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("media-playback-stop")
        self.actionStop.setIcon(icon)
        self.actionStop.setObjectName("actionStop")
        self.actionPause = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("media-playback-pause")
        self.actionPause.setIcon(icon)
        self.actionPause.setObjectName("actionPause")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionStart)
        self.menuFile.addAction(self.actionStop)
        self.menuFile.addAction(self.actionSelect_Folder)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addAction(self.actionSelect_Folder)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.InputBox.returnPressed.connect(MainWindow.InputChanged)
        self.XMin.textChanged['QString'].connect(MainWindow.InputChanged)
        self.XMax.textChanged['QString'].connect(MainWindow.InputChanged)
        self.Points.returnPressed.connect(MainWindow.InputChanged)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Y = "))
        self.lb_min.setText(_translate("MainWindow", "X Range"))
        self.lb_pts.setText(_translate("MainWindow", "Number of Points"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionStart.setText(_translate("MainWindow", "Start"))
        self.actionSelect_Folder.setText(_translate("MainWindow", "Select Folder"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionPause.setText(_translate("MainWindow", "pause"))

